version: 0.2

env:
  parameter-store:
    PASSWORD: /Production/AppPassword

phases: 
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo "📦 installing packages..."
            - echo "✅ Packages installed successfully."
    pre_build:
        commands: 
            - echo "⚙️ Testing..."
            - echo "✅ Tests passed successfully."
            - echo $PASSWORD
    build:
        commands:
            - echo "🚧 Starting compiling packages..."
            - echo "✅ Build passed successfully."
    post_build:
        commands:
            - echo "🚚 Performing post-build packing and operations..."
            - aws deploy push --application-name cfn-codedeploy-application --s3-location s3://cfn-codedeploy-revisions/revision.zip --ignore-hidden-files
            - aws deploy create-deployment --application-name cfn-codedeploy-application --s3-location bucket=cfn-codedeploy-revisions,key=revision.zip,bundleType=zip --deployment-group-name development --deployment-config-name CodeDeployDefault.OneAtATime --description "This deployment aims to deploy our code to the eligible EC2 instance(s)."
            - echo "✅ Post build successful"

artifacts:
  files:
    - '**/*'
  name: cfn-codebuild-artifacts
